# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd/e2d
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}
  asmflags:
    - all=-trimpath={{.Env.GOPATH}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
